version: '2'

services:
  mon-api:
    image: atelier/first-container
    volumes:
      - /home/stagiaire/formationDocker/atelier-compose-1:/src
    ports:
     - "5000:5000"
    networks:
      - mon-api-compose-network

  redis:
    image: "redis:alpine"
    networks:
      - mon-api-compose-network

networks:
  mon-api-compose-network:
    driver: bridge
